### ISSUE TITLE
WIthout utf8_strict, write_text fails with certain long texts

### ISSUE THREAD

**Issue by pvgoran** [Leont/file-slurp-sane#5]
So, straight to the problem. Let's say I have a utf-8 Perl string (for example, a literal string constant in a file with `use utf8;`). Let's say its utf-8 byte representation is longer than 4096 bytes, and the 4096 byte threshold breaks the byte representation of a character into two parts.

Under these conditions, if I use `write_text` to write this string, *and* I don't have `PerlIO::utf8_strict` installed, I get the following errors:

```
"\x{00e2}" does not map to utf8 at /run/current-system/sw/lib/perl5/site_perl/5.24.3/File/Slurper.pm line 73.
Close with partial character at /run/current-system/sw/lib/perl5/site_perl/5.24.3/File/Slurper.pm line 73.
```

I'm attaching [the Perl file](https://github.com/Leont/file-slurp-sane/files/1565940/slurper_utf.pl.txt) that manifests this problem. I'm running perl 5, version 24, subversion 3 (v5.24.3) built for x86_64-linux-thread-multi, File::Slurper version 0.010, under Nixos Linux.

The underlying problem seems to lie inside Perl's IO layers that are employed by `write_text` when utf_strict is not available and encoding is not specified explicitly. In this case, `:raw:encoding(utf-8)` is used as an IO layer when writing the file, and it fails to handle this kind of output properly. However, if I specify `utf8` (without a dash) as an encoding in `write_text` call, or just directly do output with `:raw:encoding(utf8)`, then this problem seems to disappear. (By the way, `:raw` doesn't influence the behaviour here, so it can be taken out of equation.)

While this seems to be an issue with core Perl, it's probably appropriate to address it in File::Slurper, either by defaulting to `utf8` instead of `utf-8`, or by declaring `utf8_strict` as a required dependency.

**Comment by Leont** [comment]
Thank you for the clear report. It was a bug in File::Slurper, it should be fixed in 0.011 (just released to CPAN). :-)

**Comment by pvgoran** [comment]
Thanks for quick resolution.

I'm somewhat concerned about the behaviour of `:encoding(utf-8)` with `fallback = FB_CROAK`.

> It was a bug in File::Slurper

So you say this behaviour is not a bug/problem of PerlIO and friends, and users of `:encoding(utf-8)` are supposed to know to add the undocumented `STOP_AT_PARTIAL` when they want to use `fallback = FB_CROAK`?..

**Comment by Leont** [comment]
> So you say this behaviour is not a bug/problem of PerlIO and friends, and users of :encoding(utf-8) are supposed to know to add the undocumented STOP_AT_PARTIAL when they want to use fallback = FB_CROAK?..

Yeah that's exactly what's needed. And indeed that is entirely undocumented. I knew about it because I've hacked PerlIO internals before, but even I forgot.

The sane resolution would be for `:encoding()` to **always** add it to the `Encode` arguments, as without it any cross-boundary character in any encoding will fail.
